spring.datasource.oracle.tns-admin=C:/cmc-auditores-y-consultores/config/WalletBDCMCAC
spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-valparaiso-1.oraclecloud.com))(connect_data=(service_name=ga1dbaf8828b599_bdcmcac_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=UserCMC
spring.datasource.password=ClaveSegura123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.jdbc.timezoneAsRegion=false
server.port=8080

