# ===============================================================
# CONFIGURACIÓN DEFINITIVA PARA ORACLE AUTONOMOUS DATABASE
# ===============================================================

# 1. Tu usuario y contraseña
spring.datasource.username=Encargo_1
spring.datasource.password=Encargo1_EA1

# 2. La URL de conexión (la "dirección larga" que ya teníamos)
spring.datasource.url=jdbc:oracle:thin:@(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.sa-valparaiso-1.oraclecloud.com))(connect_data=(service_name=g5a6c0a964dbe11_tbd_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))

# 3. Propiedad para la ubicación de la Wallet (¡LA CLAVE!)
spring.datasource.oracle.tns-admin=C:/Users/PC/Documents/4to Semestre/Taller de Base de Datos/Wallet_TBD

# 4. El driver de Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 5. Puerto del backend
server.port=8080
